api_platform:
    title: Cookbook API
    description: Api for managing cookbook recipes
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
